import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Swagger App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.links}>
          <Link href="/swagger">
            <a>
              Go to SSR swagger
            </a>
          </Link>
          <Link href="/swaggerold">
            <a>
              Go to swagger
            </a>
          </Link>
          <Link href="/redoc">
            <a>
              Go to redoc
            </a>
          </Link>
        </section>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
